/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie.reservation;



import java.awt.Color;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author 2018/E/123
 */
public class MovieReservationSystemGUI extends javax.swing.JFrame {

    /**
     * Creates new form MovieReservationSystemGUI
     */
    private int total; // Variable for calculate total cost for tickets
    private int ticketCount; // Variable for calculate ticket count
    private List<JButton> selection; // List for add selected buttons
    
    private JLabel nameLabel;      // Label for the text field
    private JTextField nameField;  // Text field for customer name
    public static boolean frameClosed = false;
    private double selectedMoviePrice;
    MovieInfo movieInfo = new MovieInfo();
    
    
    public MovieReservationSystemGUI(String movieTitle, int movieIndex, double moviePrice, MovieReservationSystem movieFrame) {
        initComponents(); // Call *before* accessing or modifying Swing components

        this.movieInfo = movieFrame.movieInfo; //Initialize MovieInfo object with passed reference
         // Initialize the movieFrame so you can access its members

        this.ticketCount = 0;
        this.total = 0;
        this.selection = new ArrayList<>();

        updateMovieTitle();
    }

    MovieReservationSystemGUI() {
         //To change body of generated methods, choose Tools | Templates.
    }
    
    private void updateMovieTitle() {
        int currentIndex = movieInfo.getCurrentMovieIndex(); // Use movieInfo.getCurrentMovieIndex()
        if (currentIndex == 0) {
            nameLbl.setFont(new java.awt.Font("Tahoma", 1, 14));
            nameLbl.setText(": Moana 2");
        } else if (currentIndex == 1) {
            nameLbl.setFont(new java.awt.Font("Tahoma", 1, 14));
            nameLbl.setText(": Hello, Love, Again");
        } else if (currentIndex == 2){
            nameLbl.setFont(new java.awt.Font("Tahoma", 1, 14));
            nameLbl.setText(": Wicked");
        }

    }
 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r1c1 = new javax.swing.JButton();
        r1c2 = new javax.swing.JButton();
        r1c3 = new javax.swing.JButton();
        r1c4 = new javax.swing.JButton();
        r1c5 = new javax.swing.JButton();
        r1c6 = new javax.swing.JButton();
        r1c7 = new javax.swing.JButton();
        r1c8 = new javax.swing.JButton();
        r1c9 = new javax.swing.JButton();
        r1c10 = new javax.swing.JButton();
        r2c1 = new javax.swing.JButton();
        r2c2 = new javax.swing.JButton();
        r2c3 = new javax.swing.JButton();
        r2c4 = new javax.swing.JButton();
        r2c5 = new javax.swing.JButton();
        r2c6 = new javax.swing.JButton();
        r2c7 = new javax.swing.JButton();
        r2c8 = new javax.swing.JButton();
        r2c9 = new javax.swing.JButton();
        r2c10 = new javax.swing.JButton();
       
        r4c3 = new javax.swing.JButton();
        r4c4 = new javax.swing.JButton();
        r4c5 = new javax.swing.JButton();
        r4c6 = new javax.swing.JButton();
        r4c7 = new javax.swing.JButton();
        r4c8 = new javax.swing.JButton();
        r5c1 = new javax.swing.JButton();
        r5c2 = new javax.swing.JButton();
        r5c3 = new javax.swing.JButton();
        r5c4 = new javax.swing.JButton();
        r5c5 = new javax.swing.JButton();
        r5c6 = new javax.swing.JButton();
        r5c7 = new javax.swing.JButton();
        r5c8 = new javax.swing.JButton();
        r5c9 = new javax.swing.JButton();
        r5c10 = new javax.swing.JButton();
        r6c1 = new javax.swing.JButton();
        r6c2 = new javax.swing.JButton();
        r6c3 = new javax.swing.JButton();
        r6c4 = new javax.swing.JButton();
        r6c5 = new javax.swing.JButton();
        r6c6 = new javax.swing.JButton();
        r6c7 = new javax.swing.JButton();
        r6c8 = new javax.swing.JButton();
        r6c9 = new javax.swing.JButton();
        r6c10 = new javax.swing.JButton();
        r7c1 = new javax.swing.JButton();
        r7c2 = new javax.swing.JButton();
        r7c3 = new javax.swing.JButton();
        r7c4 = new javax.swing.JButton();
        r7c5 = new javax.swing.JButton();
        r7c6 = new javax.swing.JButton();
        r7c7 = new javax.swing.JButton();
        r7c8 = new javax.swing.JButton();
        r7c9 = new javax.swing.JButton();
        r7c10 = new javax.swing.JButton();
        r8c1 = new javax.swing.JButton();
        r8c2 = new javax.swing.JButton();
        r8c3 = new javax.swing.JButton();
        r8c4 = new javax.swing.JButton();
        r8c5 = new javax.swing.JButton();
        r8c6 = new javax.swing.JButton();
        r8c7 = new javax.swing.JButton();
        r8c8 = new javax.swing.JButton();
        r8c9 = new javax.swing.JButton();
        r8c10 = new javax.swing.JButton();
        r9c1 = new javax.swing.JButton();
        r9c2 = new javax.swing.JButton();
        r9c3 = new javax.swing.JButton();
        r9c4 = new javax.swing.JButton();
        r9c5 = new javax.swing.JButton();
        r9c6 = new javax.swing.JButton();
        r9c7 = new javax.swing.JButton();
        r9c8 = new javax.swing.JButton();
        r9c9 = new javax.swing.JButton();
        r9c10 = new javax.swing.JButton();
        r10c3 = new javax.swing.JButton();
        r10c4 = new javax.swing.JButton();
        r10c5 = new javax.swing.JButton();
        r10c6 = new javax.swing.JButton();
        r10c7 = new javax.swing.JButton();
        r10c8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookSeats = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        ticketCounter = new javax.swing.JLabel();
        totalCounter = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        seatCounter = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Reservation Application");
        setResizable(false);
        Container contentPane = getContentPane();
        contentPane.setBackground(new Color(237, 239, 207));

        r1c1.setBackground(new java.awt.Color(102, 102, 102));
        r1c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c1.setText("1");
        r1c1.setName("R1C1"); // NOI18N
        r1c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c2.setBackground(new java.awt.Color(102, 102, 102));
        r1c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c2.setText("2");
        r1c2.setName("R1C2"); // NOI18N
        r1c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c3.setBackground(new java.awt.Color(102, 102, 102));
        r1c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c3.setText("3");
        r1c3.setName("R1C3"); // NOI18N
        r1c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c4.setBackground(new java.awt.Color(102, 102, 102));
        r1c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c4.setText("4");
        r1c4.setName("R1C4"); // NOI18N
        r1c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c5.setBackground(new java.awt.Color(102, 102, 102));
        r1c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c5.setText("5");
        r1c5.setName("R1C5"); // NOI18N
        r1c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c6.setBackground(new java.awt.Color(102, 102, 102));
        r1c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c6.setText("6");
        r1c6.setName("R1C6"); // NOI18N
        r1c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c7.setBackground(new java.awt.Color(102, 102, 102));
        r1c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c7.setText("7");
        r1c7.setName("R1C7"); // NOI18N
        r1c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c8.setBackground(new java.awt.Color(102, 102, 102));
        r1c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c8.setText("8");
        r1c8.setName("R1C8"); // NOI18N
        r1c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c9.setBackground(new java.awt.Color(102, 102, 102));
        r1c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c9.setText("9");
        r1c9.setName("R1C9"); // NOI18N
        r1c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r1c10.setBackground(new java.awt.Color(102, 102, 102));
        r1c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r1c10.setText("10");
        r1c10.setName("R1C10"); // NOI18N
        r1c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c1.setBackground(new java.awt.Color(102, 102, 102));
        r2c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c1.setText("1");
        r2c1.setName("R2C1"); // NOI18N
        r2c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c2.setBackground(new java.awt.Color(102, 102, 102));
        r2c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c2.setText("2");
        r2c2.setName("R2C2"); // NOI18N
        r2c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c3.setBackground(new java.awt.Color(102, 102, 102));
        r2c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c3.setText("3");
        r2c3.setName("R2C3"); // NOI18N
        r2c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c4.setBackground(new java.awt.Color(102, 102, 102));
        r2c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c4.setText("4");
        r2c4.setName("R2C4"); // NOI18N
        r2c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c5.setBackground(new java.awt.Color(102, 102, 102));
        r2c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c5.setText("5");
        r2c5.setName("R2C5"); // NOI18N
        r2c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c6.setBackground(new java.awt.Color(102, 102, 102));
        r2c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c6.setText("6");
        r2c6.setName("R2C6"); // NOI18N
        r2c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c7.setBackground(new java.awt.Color(102, 102, 102));
        r2c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c7.setText("7");
        r2c7.setName("R2C7"); // NOI18N
        r2c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c8.setBackground(new java.awt.Color(102, 102, 102));
        r2c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c8.setText("8");
        r2c8.setName("R2C8"); // NOI18N
        r2c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c9.setBackground(new java.awt.Color(102, 102, 102));
        r2c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c9.setText("9");
        r2c9.setName("R2C9"); // NOI18N
        r2c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r2c10.setBackground(new java.awt.Color(102, 102, 102));
        r2c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r2c10.setText("10");
        r2c10.setName("R2C10"); // NOI18N
        r2c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

      

        r4c3.setBackground(new java.awt.Color(102, 102, 102));
        r4c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r4c3.setText("3");
        r4c3.setName("R4C3"); // NOI18N
        r4c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r4c4.setBackground(new java.awt.Color(102, 102, 102));
        r4c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r4c4.setText("4");
        r4c4.setName("R4C4"); // NOI18N
        r4c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r4c5.setBackground(new java.awt.Color(102, 102, 102));
        r4c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r4c5.setText("5");
        r4c5.setName("R4C5"); // NOI18N
        r4c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r4c6.setBackground(new java.awt.Color(102, 102, 102));
        r4c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r4c6.setText("6");
        r4c6.setName("R4C6"); // NOI18N
        r4c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r4c7.setBackground(new java.awt.Color(102, 102, 102));
        r4c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r4c7.setText("7");
        r4c7.setName("R4C7"); // NOI18N
        r4c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r4c8.setBackground(new java.awt.Color(102, 102, 102));
        r4c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r4c8.setText("8");
        r4c8.setName("R4C8"); // NOI18N
        r4c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c1.setBackground(new java.awt.Color(102, 102, 102));
        r5c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c1.setText("1");
        r5c1.setName("R5C1"); // NOI18N
        r5c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c2.setBackground(new java.awt.Color(102, 102, 102));
        r5c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c2.setText("2");
        r5c2.setName("R5C2"); // NOI18N
        r5c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c3.setBackground(new java.awt.Color(102, 102, 102));
        r5c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c3.setText("3");
        r5c3.setName("R5C3"); // NOI18N
        r5c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c4.setBackground(new java.awt.Color(102, 102, 102));
        r5c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c4.setText("4");
        r5c4.setName("R5C4"); // NOI18N
        r5c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c5.setBackground(new java.awt.Color(102, 102, 102));
        r5c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c5.setText("5");
        r5c5.setName("R5C5"); // NOI18N
        r5c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c6.setBackground(new java.awt.Color(102, 102, 102));
        r5c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c6.setText("6");
        r5c6.setName("R5C6"); // NOI18N
        r5c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c7.setBackground(new java.awt.Color(102, 102, 102));
        r5c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c7.setText("7");
        r5c7.setName("R5C7"); // NOI18N
        r5c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c8.setBackground(new java.awt.Color(102, 102, 102));
        r5c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c8.setText("8");
        r5c8.setName("R5C8"); // NOI18N
        r5c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c9.setBackground(new java.awt.Color(102, 102, 102));
        r5c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c9.setText("9");
        r5c9.setName("R5C9"); // NOI18N
        r5c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r5c10.setBackground(new java.awt.Color(102, 102, 102));
        r5c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r5c10.setText("10");
        r5c10.setName("R5C10"); // NOI18N
        r5c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c1.setBackground(new java.awt.Color(102, 102, 102));
        r6c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c1.setText("1");
        r6c1.setName("R6C1"); // NOI18N
        r6c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c2.setBackground(new java.awt.Color(102, 102, 102));
        r6c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c2.setText("2");
        r6c2.setName("R6C2"); // NOI18N
        r6c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c3.setBackground(new java.awt.Color(102, 102, 102));
        r6c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c3.setText("3");
        r6c3.setName("R6C3"); // NOI18N
        r6c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c4.setBackground(new java.awt.Color(102, 102, 102));
        r6c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c4.setText("4");
        r6c4.setName("R6C4"); // NOI18N
        r6c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c5.setBackground(new java.awt.Color(102, 102, 102));
        r6c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c5.setText("5");
        r6c5.setName("R6C5"); // NOI18N
        r6c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c6.setBackground(new java.awt.Color(102, 102, 102));
        r6c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c6.setText("6");
        r6c6.setName("R6C6"); // NOI18N
        r6c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c7.setBackground(new java.awt.Color(102, 102, 102));
        r6c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c7.setText("7");
        r6c7.setName("R6C7"); // NOI18N
        r6c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c8.setBackground(new java.awt.Color(102, 102, 102));
        r6c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c8.setText("8");
        r6c8.setName("R6C8"); // NOI18N
        r6c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c9.setBackground(new java.awt.Color(102, 102, 102));
        r6c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c9.setText("9");
        r6c9.setName("R6C9"); // NOI18N
        r6c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r6c10.setBackground(new java.awt.Color(102, 102, 102));
        r6c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r6c10.setText("10");
        r6c10.setName("R6C10"); // NOI18N
        r6c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c1.setBackground(new java.awt.Color(102, 102, 102));
        r7c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c1.setText("1");
        r7c1.setName("R7C1"); // NOI18N
        r7c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c2.setBackground(new java.awt.Color(102, 102, 102));
        r7c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c2.setText("2");
        r7c2.setName("R7C2"); // NOI18N
        r7c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c3.setBackground(new java.awt.Color(102, 102, 102));
        r7c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c3.setText("3");
        r7c3.setName("R7C3"); // NOI18N
        r7c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c4.setBackground(new java.awt.Color(102, 102, 102));
        r7c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c4.setText("4");
        r7c4.setName("R7C4"); // NOI18N
        r7c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c5.setBackground(new java.awt.Color(102, 102, 102));
        r7c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c5.setText("5");
        r7c5.setName("R7C5"); // NOI18N
        r7c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c6.setBackground(new java.awt.Color(102, 102, 102));
        r7c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c6.setText("6");
        r7c6.setName("R7C6"); // NOI18N
        r7c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c7.setBackground(new java.awt.Color(102, 102, 102));
        r7c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c7.setText("7");
        r7c7.setName("R7C7"); // NOI18N
        r7c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c8.setBackground(new java.awt.Color(102, 102, 102));
        r7c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c8.setText("8");
        r7c8.setName("R7C8"); // NOI18N
        r7c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c9.setBackground(new java.awt.Color(102, 102, 102));
        r7c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c9.setText("9");
        r7c9.setName("R7C9"); // NOI18N
        r7c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r7c10.setBackground(new java.awt.Color(102, 102, 102));
        r7c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r7c10.setText("10");
        r7c10.setName("R7C10"); // NOI18N
        r7c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c1.setBackground(new java.awt.Color(102, 102, 102));
        r8c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c1.setText("1");
        r8c1.setName("R8C1"); // NOI18N
        r8c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c2.setBackground(new java.awt.Color(102, 102, 102));
        r8c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c2.setText("2");
        r8c2.setName("R8C2"); // NOI18N
        r8c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c3.setBackground(new java.awt.Color(102, 102, 102));
        r8c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c3.setText("3");
        r8c3.setName("R8C3"); // NOI18N
        r8c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c4.setBackground(new java.awt.Color(102, 102, 102));
        r8c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c4.setText("4");
        r8c4.setName("R8C4"); // NOI18N
        r8c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c5.setBackground(new java.awt.Color(102, 102, 102));
        r8c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c5.setText("5");
        r8c5.setName("R8C5"); // NOI18N
        r8c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c6.setBackground(new java.awt.Color(102, 102, 102));
        r8c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c6.setText("6");
        r8c6.setName("R8C6"); // NOI18N
        r8c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c7.setBackground(new java.awt.Color(102, 102, 102));
        r8c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c7.setText("7");
        r8c7.setName("R8C7"); // NOI18N
        r8c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c8.setBackground(new java.awt.Color(102, 102, 102));
        r8c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c8.setText("8");
        r8c8.setName("R8C8"); // NOI18N
        r8c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c9.setBackground(new java.awt.Color(102, 102, 102));
        r8c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c9.setText("9");
        r8c9.setName("R8C9"); // NOI18N
        r8c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r8c10.setBackground(new java.awt.Color(102, 102, 102));
        r8c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r8c10.setText("10");
        r8c10.setName("R8C10"); // NOI18N
        r8c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c1.setBackground(new java.awt.Color(102, 102, 102));
        r9c1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c1.setText("1");
        r9c1.setName("R9C1"); // NOI18N
        r9c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c2.setBackground(new java.awt.Color(102, 102, 102));
        r9c2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c2.setText("2");
        r9c2.setName("R9C2"); // NOI18N
        r9c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c3.setBackground(new java.awt.Color(102, 102, 102));
        r9c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c3.setText("3");
        r9c3.setName("R9C3"); // NOI18N
        r9c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c4.setBackground(new java.awt.Color(102, 102, 102));
        r9c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c4.setText("4");
        r9c4.setName("R9C4"); // NOI18N
        r9c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c5.setBackground(new java.awt.Color(102, 102, 102));
        r9c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c5.setText("5");
        r9c5.setName("R9C5"); // NOI18N
        r9c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c6.setBackground(new java.awt.Color(102, 102, 102));
        r9c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c6.setText("6");
        r9c6.setName("R9C6"); // NOI18N
        r9c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c7.setBackground(new java.awt.Color(102, 102, 102));
        r9c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c7.setText("7");
        r9c7.setName("R9C7"); // NOI18N
        r9c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c8.setBackground(new java.awt.Color(102, 102, 102));
        r9c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c8.setText("8");
        r9c8.setName("R9C8"); // NOI18N
        r9c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c9.setBackground(new java.awt.Color(102, 102, 102));
        r9c9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c9.setText("9");
        r9c9.setName("R9C9"); // NOI18N
        r9c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r9c10.setBackground(new java.awt.Color(102, 102, 102));
        r9c10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r9c10.setText("10");
        r9c10.setName("R9C10"); // NOI18N
        r9c10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r10c3.setBackground(new java.awt.Color(102, 102, 102));
        r10c3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r10c3.setText("3");
        r10c3.setName("R10C3"); // NOI18N
        r10c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r10c4.setBackground(new java.awt.Color(102, 102, 102));
        r10c4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r10c4.setText("4");
        r10c4.setName("R10C4"); // NOI18N
        r10c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r10c5.setBackground(new java.awt.Color(102, 102, 102));
        r10c5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r10c5.setText("5");
        r10c5.setName("R10C5"); // NOI18N
        r10c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r10c6.setBackground(new java.awt.Color(102, 102, 102));
        r10c6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r10c6.setText("6");
        r10c6.setName("R10C6"); // NOI18N
        r10c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r10c7.setBackground(new java.awt.Color(102, 102, 102));
        r10c7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r10c7.setText("7");
        r10c7.setName("R10C7"); // NOI18N
        r10c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        r10c8.setBackground(new java.awt.Color(102, 102, 102));
        r10c8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        r10c8.setText("8");
        r10c8.setName("R10C8"); // NOI18N
        r10c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Multiplex Theatre Showing Screen 1");

        jLabel2.setBackground(new java.awt.Color(255, 153, 51));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SCREEN");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Movie");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Tickets");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Total");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("Seats");

        bookSeats.setBackground(new java.awt.Color(255, 153, 51));
        bookSeats.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        bookSeats.setForeground(new java.awt.Color(255, 255, 255));
        bookSeats.setText("Book Now");
        bookSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSeatsActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Available");

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 51));
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Sold");

        jLabel12.setBackground(new java.awt.Color(0, 255, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 51));
        jLabel12.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Selected");
        
      
            
        
    
      
        
        
        timeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeLbl.setText(": April 03, 21:00");

        ticketCounter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ticketCounter.setText(": 0");

        totalCounter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalCounter.setText(": 0 PHP");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("1");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("2");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("5");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("6");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("7");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("8");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("10");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("9");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("3");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("4");

        seatCounter.setEditable(false);
        seatCounter.setBackground(new java.awt.Color(240, 240, 240));
        seatCounter.setColumns(20);
        seatCounter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seatCounter.setRows(5);
        seatCounter.setText(": ");
        jScrollPane1.setViewportView(seatCounter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r2c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                
                                .addGap(36, 36, 36)
                              
                                .addGap(100, 100, 100)
                                .addComponent(r4c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r4c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r4c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r4c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r4c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r4c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r5c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r5c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r6c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r6c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticketCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(r10c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r10c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r10c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r10c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r10c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r10c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r7c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r7c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r8c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r8c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r9c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bookSeats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r1c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r2c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ticketCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            
                            .addComponent(r4c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r4c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r4c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r4c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r4c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r4c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r5c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r5c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r6c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r6c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r7c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r8c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r8c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r9c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r9c10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(r10c3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r10c4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r10c5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r10c6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r10c7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(r10c8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * This method is used to perform the operations in application 
     * @param evt 
     */
    private void btnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClick
        JButton clickedBtn = (JButton)evt.getSource(); // Identifies the clicked button in the appication 
        
        int price = (int) movieInfo.getSelectedMoviePrice();
        Color green = new Color(0,255,0); // Creating green color
        Color gray = new Color(102,102,102); // Creating gray color
        if(clickedBtn.getBackground().equals(gray)){ // If an user clicked gray button
            if(clickedBtn.getName().contains("R1")){ // If user clicked a last row gray button
                this.total += price; // Increase total cost by 20
            }
            else{ // If user clicked other gray button
                this.total += price; // Increase total cost by 12
            }
            clickedBtn.setBackground(green); // Setting clicked button background to green
            this.ticketCount += 1; // Increase ticket count by 1
            this.totalCounter.setText(": " + Integer.toString(total) + " PHP"); // Display total in specified label
            this.seatCounter.setText(seatCounter.getText().concat(clickedBtn.getName()) + "  ");  // Display selected seats in specified label
            this.selection.add(clickedBtn); // Add selected button to list
        }
        else if(clickedBtn.getBackground().equals(green)){ // If an user clicked green button
            if(clickedBtn.getName().contains("R1")){ // If user clicked a last row green button
                this.total -= price; // Decrease total cost by 20
            }
            else{ // If user clicked other green button
                this.total -= price;  // Decrease total cost by 12
            }
            clickedBtn.setBackground(gray); // Setting clicked button background to gray
            this.ticketCount -= 1; // Decrease ticket count by 1
            this.totalCounter.setText(": " + Integer.toString(total) + " PHP"); // Display total in specified label
            this.seatCounter.setText(seatCounter.getText().replaceAll(clickedBtn.getName() + "  ", "")); // Remove selected seats from specified label
            this.selection.remove(clickedBtn); // Remove clicked button from the list
        }
        this.ticketCounter.setText(": " + Integer.toString(ticketCount)); // Display amount of tickets in specified label
        
    }//GEN-LAST:event_btnClick
    
    /**
     * This method includes things that need to happen when 'BOOK' button clicked by user
     * @param evt 
     */
    public void bookSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSeatsActionPerformed
        
        Color red = new Color(255, 0, 0);
        TicketInformation ticket = new TicketInformation(); // Creating new ticket to show ticket infromati
        ticket.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
         // Stop execution if the frame is closed
        
        passInfo(this.nameLbl.getText(), this.timeLbl.getText(), this.ticketCounter.getText(), this.totalCounter.getText(), this.seatCounter.getText()); // Pass tickect information to second frame(Ticket information)
        ticket.setVisible(true); 
        
        this.selection.forEach(selectedBtns -> {
        
        selectedBtns.setBackground(red);
        this.ticketCounter.setText(":");
        this.totalCounter.setText(":");
        this.seatCounter.setText(":");
        this.ticketCount = 0;
        this.total = 0;
        if (this.selection.size() == 84) {
            this.bookSeats.setEnabled(false);
        }
    });

        
        
    }

 
       
    
    //GEN-LAST:event_bookSeatsActionPerformed
    
    /**
     * This method is used to pass information in this main frame to 'Ticket Information' frame
     * @param name Movie name
     * @param time Movie time
     * @param tickets Number of tickets
     * @param total Total cost
     * @param seats seats booked
     */
    public void passInfo(String name, String time, String tickets, String total, String seats){
        // Setting values of 'Ticket Information' frame
        TicketInformation.nameLbl.setText(name); 
        TicketInformation.timeLbl.setText(time);
        TicketInformation.ticketCounter.setText(tickets);
        TicketInformation.totalCounter.setText(total);
        TicketInformation.seatsLbl.setText(seats);
    };
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton r10c3;
    private javax.swing.JButton r10c4;
    private javax.swing.JButton r10c5;
    private javax.swing.JButton r10c6;
    private javax.swing.JButton r10c7;
    private javax.swing.JButton r10c8;
    private javax.swing.JButton r1c1;
    private javax.swing.JButton r1c10;
    private javax.swing.JButton r1c2;
    private javax.swing.JButton r1c3;
    private javax.swing.JButton r1c4;
    private javax.swing.JButton r1c5;
    private javax.swing.JButton r1c6;
    private javax.swing.JButton r1c7;
    private javax.swing.JButton r1c8;
    private javax.swing.JButton r1c9;
    private javax.swing.JButton r2c1;
    private javax.swing.JButton r2c10;
    private javax.swing.JButton r2c2;
    private javax.swing.JButton r2c3;
    private javax.swing.JButton r2c4;
    private javax.swing.JButton r2c5;
    private javax.swing.JButton r2c6;
    private javax.swing.JButton r2c7;
    private javax.swing.JButton r2c8;
    private javax.swing.JButton r2c9;
   
    private javax.swing.JButton r4c3;
    private javax.swing.JButton r4c4;
    private javax.swing.JButton r4c5;
    private javax.swing.JButton r4c6;
    private javax.swing.JButton r4c7;
    private javax.swing.JButton r4c8;
    private javax.swing.JButton r5c1;
    private javax.swing.JButton r5c10;
    private javax.swing.JButton r5c2;
    private javax.swing.JButton r5c3;
    private javax.swing.JButton r5c4;
    private javax.swing.JButton r5c5;
    private javax.swing.JButton r5c6;
    private javax.swing.JButton r5c7;
    private javax.swing.JButton r5c8;
    private javax.swing.JButton r5c9;
    private javax.swing.JButton r6c1;
    private javax.swing.JButton r6c10;
    private javax.swing.JButton r6c2;
    private javax.swing.JButton r6c3;
    private javax.swing.JButton r6c4;
    private javax.swing.JButton r6c5;
    private javax.swing.JButton r6c6;
    private javax.swing.JButton r6c7;
    private javax.swing.JButton r6c8;
    private javax.swing.JButton r6c9;
    private javax.swing.JButton r7c1;
    private javax.swing.JButton r7c10;
    private javax.swing.JButton r7c2;
    private javax.swing.JButton r7c3;
    private javax.swing.JButton r7c4;
    private javax.swing.JButton r7c5;
    private javax.swing.JButton r7c6;
    private javax.swing.JButton r7c7;
    private javax.swing.JButton r7c8;
    private javax.swing.JButton r7c9;
    private javax.swing.JButton r8c1;
    private javax.swing.JButton r8c10;
    private javax.swing.JButton r8c2;
    private javax.swing.JButton r8c3;
    private javax.swing.JButton r8c4;
    private javax.swing.JButton r8c5;
    private javax.swing.JButton r8c6;
    private javax.swing.JButton r8c7;
    private javax.swing.JButton r8c8;
    private javax.swing.JButton r8c9;
    private javax.swing.JButton r9c1;
    private javax.swing.JButton r9c10;
    private javax.swing.JButton r9c2;
    private javax.swing.JButton r9c3;
    private javax.swing.JButton r9c4;
    private javax.swing.JButton r9c5;
    private javax.swing.JButton r9c6;
    private javax.swing.JButton r9c7;
    private javax.swing.JButton r9c8;
    private javax.swing.JButton r9c9;
    private javax.swing.JTextArea seatCounter;
    private javax.swing.JLabel ticketCounter;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JLabel totalCounter;
    // End of variables declaration//GEN-END:variables
}